### ISSUE TITLE
Is this a replacement for https://github.com/lightblue-platform/lightblue-esb-hook

### ISSUE THREAD

**Issue by dcrissman** [esbtools/lightblue-notification-hook#2]
The lightblue-esb-hook was always very specific to esb and probably does not belong as a top level lightblue project.

If this is a replacement, then lets talk about removing the other project? If not, then how can we merge them?

**Comment by alechenninger** [comment]
This is a replacement. It's similar, but the data model and configuration is different.

**Comment by alechenninger** [comment]
As far as removing the other project, I think this is up to you? We're not using it. As far as I understand it we'll be migrating the current integration that is using it to this project (and the esbtools/event-handler).

**Comment by alechenninger** [comment]
@dcrissman Do you think I can close this now?
